version: '3'
services: 
  ride-hailing-api: 
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports: 
      - '5010:3000'
    depends_on: 
      - ride-hailing-db
    environment: 
        - NODE_ENV=production
  ride-hailing-db:
    image: mysql:8.0
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: 'ride_hailing_api'
    ports: 
        - '5020:3306'
    volumes: 
        - "db:/var/lib/mysql:rw"
volumes:
    db: